Repository nasa/cFS-GroundSystem, pull requests merged in 2020-09, with the labels that each got.

#127 Integration Candidate: 2020-08-26
  README.md
  Subsystems/Commands-Telemetry.md
  Subsystems/Commands-Telemetry.txt
  _version.py
Labels: IC-20200826

#130 Fix #93, Refactor and resolve cast align warning
  Subsystems/cmdUtil/SendUdp.c
Labels: CCB-20200902, IC-20200902, bug

#129 Fix #128, strncpy should result in null term
  Subsystems/cmdUtil/cmdUtil.c
Labels: CCB-20200902, IC-20200902, code reviewed

#133 Integration Candidate: 2020-09-02
  README.md
  Subsystems/cmdUtil/SendUdp.c
  Subsystems/cmdUtil/cmdUtil.c
  _version.py
Labels: IC-20200902

#135 Integration Candidate: 2020-09-09
  README.md
  Subsystems/cmdGui/CHeaderParser.py
  _version.py
Labels: IC-20200909
