Repository nasa/cFS-GroundSystem, pull requests merged in 2020-05, with the labels that each got.

#77 Fix #76, warnings on strncpy
  Subsystems/cmdUtil/cmdUtil.c
Labels: CCB-20200429, IC-20200429, bug, code reviewed

#78 Fix typos
  RoutingService.py
  Subsystems/cmdGui/CHeaderParser.py
  Subsystems/cmdGui/CommandSystem.py
  Subsystems/cmdGui/Parameter.py
  Subsystems/tlmGUI/GenericTelemetry.py
  Subsystems/tlmGUI/TelemetrySystem.py
Labels: CCB-20200429, IC-20200429, code reviewed, enhancement

#84 Fix #83, Add event type and ID to message
  Subsystems/tlmGUI/EventMessage.py
Labels: CCB-20200506, IC-20200429, code reviewed

#86 Integration Candidate COMBINED 2020-04-29 and 2020-05-06
  Guide-GroundSystem.md
  Guide-GroundSystem.txt
  README.md
  RoutingService.py
  Subsystems/cmdGui/CHeaderParser.py
  Subsystems/cmdGui/CommandSystem.py
  Subsystems/cmdGui/Parameter.py
  Subsystems/cmdUtil/cmdUtil.c
  Subsystems/tlmGUI/EventMessage.py
  Subsystems/tlmGUI/GenericTelemetry.py
  Subsystems/tlmGUI/TelemetrySystem.py
Labels: IC-20200429

#85 Fix #72 and #71, Upgrades to PyQt 5 and sequence count fix
  .gitignore
  GroundSystem.py
  Guide-GroundSystem.md
  Guide-GroundSystem.txt
  MainWindow.py
  RoutingService.py
  Subsystems/Commands-Telemetry.txt
  Subsystems/cmdGui/CHeaderParser.py
  Subsystems/cmdGui/CommandParser.py
  Subsystems/cmdGui/CommandSystem.py
  Subsystems/cmdGui/CommandSystemDialog.py
  Subsystems/cmdGui/CommandSystemDialog.ui
  Subsystems/cmdGui/GenericCommandDialog.py
  Subsystems/cmdGui/GenericCommandDialog.ui
  Subsystems/cmdGui/HTMLDocsParser.py
  Subsystems/cmdGui/Parameter.py
  Subsystems/cmdGui/ParameterDialog.py
  Subsystems/cmdGui/ParameterDialog.ui
  Subsystems/cmdGui/UdpCommands.py
  Subsystems/cmdGui/quick-buttons.txt
  Subsystems/tlmGUI/EventMessage.py
  Subsystems/tlmGUI/EventMessageDialog.py
  Subsystems/tlmGUI/EventMessageDialog.ui
  Subsystems/tlmGUI/GenericTelemetry.py
  Subsystems/tlmGUI/GenericTelemetryDialog.py
  Subsystems/tlmGUI/GenericTelemetryDialog.ui
  Subsystems/tlmGUI/TelemetrySystem.py
  Subsystems/tlmGUI/TelemetrySystemDialog.py
  Subsystems/tlmGUI/TelemetrySystemDialog.ui
  TlmMQRecv.py
  TlmUDPSender.py
Labels: CCB-20200513

#90 Integration Candidate: 2020-05-13
  .gitignore
  GroundSystem.py
  Guide-GroundSystem.md
  Guide-GroundSystem.txt
  MainWindow.py
  README.md
  RoutingService.py
  Subsystems/Commands-Telemetry.txt
  Subsystems/cmdGui/CHeaderParser.py
  Subsystems/cmdGui/CommandParser.py
  Subsystems/cmdGui/CommandSystem.py
  Subsystems/cmdGui/CommandSystemDialog.py
  Subsystems/cmdGui/CommandSystemDialog.ui
  Subsystems/cmdGui/GenericCommandDialog.py
  Subsystems/cmdGui/GenericCommandDialog.ui
  Subsystems/cmdGui/HTMLDocsParser.py
  Subsystems/cmdGui/Parameter.py
  Subsystems/cmdGui/ParameterDialog.py
  Subsystems/cmdGui/ParameterDialog.ui
  Subsystems/cmdGui/UdpCommands.py
  Subsystems/cmdGui/quick-buttons.txt
  Subsystems/tlmGUI/EventMessage.py
  Subsystems/tlmGUI/EventMessageDialog.py
  Subsystems/tlmGUI/EventMessageDialog.ui
  Subsystems/tlmGUI/GenericTelemetry.py
  Subsystems/tlmGUI/GenericTelemetryDialog.py
  Subsystems/tlmGUI/GenericTelemetryDialog.ui
  Subsystems/tlmGUI/TelemetrySystem.py
  Subsystems/tlmGUI/TelemetrySystemDialog.py
  Subsystems/tlmGUI/TelemetrySystemDialog.ui
  TlmMQRecv.py
  TlmUDPSender.py
Labels: IC-20200513

#87 Fix #75, Convert a Guide-Loading-Tables.txt file to markdown
  Guide-Loading-Tables.md
  Guide-Loading-Tables.txt
Labels: IC-20200520, code reviewed, docs, enhancement
