Repository nasa/cFS-GroundSystem, pull requests merged in 2020-04, with the labels that each got.

#66 Fix #65, CCSDS Command Secondary Header Endian Agnostic
  Subsystems/cmdUtil/cmdUtil.c
Labels: CCB - 20200401, IC - 20200401, bug, code reviewed

#69 Integration Candidate 2020-04-01
  Guide-GroundSystem.txt
  README.md
  Subsystems/cmdUtil/cmdUtil.c
Labels: IC - 20200401

#70 Fix #13, Remove .DS_Store file, add this file to .gitignore.
  .gitignore
  Subsystems/cmdUtil/.DS_Store
Labels: CCB - 20200401, IC - 20200415, code reviewed, enhancement

#68 Fix #67, Remove mission_inc reference
  Subsystems/cmdGui/HTMLDocsParser.py
Labels: CCB - 20200415, IC - 20200415, code reviewed, enhancement

#73 Fix #9, Convert Guide-GroundSystem.txt file content to Markdown
  Guide-GroundSystem.md
Labels: CCB - 20200415, IC - 20200415, code reviewed, docs
