Repository nasa/cFS-GroundSystem, pull requests merged in 2020-06, with the labels that each got.

#92 cFS Header Version 2 (includes CCSDS Extended header) support and major update
  Subsystems/cmdUtil/Makefile
  Subsystems/cmdUtil/SendUdp.c
  Subsystems/cmdUtil/SendUdp.h
  Subsystems/cmdUtil/cmdUtil.c
  Subsystems/cmdUtil/cmdUtil.sln
  Subsystems/cmdUtil/tests.sh
Labels: CCB-20200527, IC-20200527, enhancement

#101 Integration Candidate: 2020-05-27
  Guide-GroundSystem.md
  Guide-GroundSystem.txt
  README.md
  Subsystems/cmdUtil/Makefile
  Subsystems/cmdUtil/SendUdp.c
  Subsystems/cmdUtil/SendUdp.h
  Subsystems/cmdUtil/cmdUtil.c
  Subsystems/cmdUtil/cmdUtil.sln
  Subsystems/cmdUtil/tests.sh
Labels: IC-20200527

#100 Fix #98, Refactor individual UI elements to tables
  GroundSystem.py
  Subsystems/cmdGui/CHeaderParser.py
  Subsystems/cmdGui/CommandSystem.py
  Subsystems/cmdGui/CommandSystemDialog.py
  Subsystems/cmdGui/CommandSystemDialog.ui
  Subsystems/cmdGui/GenericCommandDialog.py
  Subsystems/cmdGui/GenericCommandDialog.ui
  Subsystems/cmdGui/Parameter.py
  Subsystems/cmdGui/ParameterDialog.py
  Subsystems/cmdGui/ParameterDialog.ui
  Subsystems/cmdGui/UdpCommands.py
  Subsystems/cmdGui/Ui_CommandSystemDialog.py
  Subsystems/cmdGui/Ui_GenericCommandDialog.py
  Subsystems/cmdGui/Ui_ParameterDialog.py
  Subsystems/tlmGUI/EventMessage.py
  Subsystems/tlmGUI/GenericTelemetry.py
  Subsystems/tlmGUI/GenericTelemetryDialog.py
  Subsystems/tlmGUI/GenericTelemetryDialog.ui
  Subsystems/tlmGUI/TelemetrySystem.py
  Subsystems/tlmGUI/TelemetrySystemDialog.py
  Subsystems/tlmGUI/TelemetrySystemDialog.ui
  Subsystems/tlmGUI/Ui_EventMessageDialog.py
  Subsystems/tlmGUI/Ui_GenericTelemetryDialog.py
  Subsystems/tlmGUI/Ui_TelemetrySystemDialog.py
  TlmMQRecv.py
Labels: CCB-20200617, IC-20200617, code reviewed

#106 Fix #104, Short term build fix for implicit endian functions
  Subsystems/cmdUtil/cmdUtil.c
Labels: CCB - Fast Track, CCB-READY, IC-20200617, bug

#107 Integration Candidate: 2020-06-17
  GroundSystem.py
  Guide-GroundSystem.md
  Guide-GroundSystem.txt
  README.md
  Subsystems/cmdGui/CHeaderParser.py
  Subsystems/cmdGui/CommandSystem.py
  Subsystems/cmdGui/CommandSystemDialog.py
  Subsystems/cmdGui/CommandSystemDialog.ui
  Subsystems/cmdGui/GenericCommandDialog.py
  Subsystems/cmdGui/GenericCommandDialog.ui
  Subsystems/cmdGui/Parameter.py
  Subsystems/cmdGui/ParameterDialog.py
  Subsystems/cmdGui/ParameterDialog.ui
  Subsystems/cmdGui/UdpCommands.py
  Subsystems/cmdGui/Ui_CommandSystemDialog.py
  Subsystems/cmdGui/Ui_GenericCommandDialog.py
  Subsystems/cmdGui/Ui_ParameterDialog.py
  Subsystems/cmdUtil/cmdUtil.c
  Subsystems/tlmGUI/EventMessage.py
  Subsystems/tlmGUI/GenericTelemetry.py
  Subsystems/tlmGUI/GenericTelemetryDialog.py
  Subsystems/tlmGUI/GenericTelemetryDialog.ui
  Subsystems/tlmGUI/TelemetrySystem.py
  Subsystems/tlmGUI/TelemetrySystemDialog.py
  Subsystems/tlmGUI/TelemetrySystemDialog.ui
  Subsystems/tlmGUI/Ui_EventMessageDialog.py
  Subsystems/tlmGUI/Ui_GenericTelemetryDialog.py
  Subsystems/tlmGUI/Ui_TelemetrySystemDialog.py
  TlmMQRecv.py
Labels: IC-20200617
