Repository nasa/cFS-GroundSystem, pull requests merged in 2020-07, with the labels that each got.

#96 Fix #46 Recommended lgtm python issues
  Subsystems/cmdGui/Ui_CommandSystemDialog.py
  Subsystems/cmdGui/Ui_GenericCommandDialog.py
  Subsystems/cmdGui/Ui_ParameterDialog.py
  Subsystems/tlmGUI/Ui_GenericTelemetryDialog.py
  Subsystems/tlmGUI/Ui_TelemetrySystemDialog.py
Labels: CCB-20200624, IC-20200624, code reviewed, enhancement

#113 Resolve #112, add build number and baseline
  .gitignore
  GroundSystem.py
  _version.py
Labels: IC-20200624

#109 Integration Candidate: 2020-06-24
  .gitignore
  GroundSystem.py
  MainWindow.ui
  README.md
  RoutingService.py
  Subsystems/cmdGui/CommandSystem.py
  Subsystems/cmdGui/MiniCmdUtil.py
  Subsystems/cmdGui/Parameter.py
  Subsystems/cmdGui/UdpCommands.py
  Subsystems/tlmGUI/EventMessage.py
  Subsystems/tlmGUI/GenericTelemetry.py
  Subsystems/tlmGUI/GenericTelemetryDialog.ui
  Subsystems/tlmGUI/Ui_GenericTelemetryDialog.py
  Ui_MainWindow.py
  _version.py
Labels: IC-20200624

#117 Fix #99, Guide format fix
  Guide-GroundSystem.md
  Guide-GroundSystem.txt
Labels: CCB-20200729, CCB-FastTrack, docs
