Repository nasa/cFS-GroundSystem, pull requests merged in 2021-07, with the labels that each got.

#185 Fix #184, Update tlm for ES Blockstats/memstats and TBL HK
  Subsystems/tlmGUI/cfe-es-blockstats_1-tlm.txt
  Subsystems/tlmGUI/cfe-es-memstats-tlm.txt
  Subsystems/tlmGUI/cfe-tbl-hk-tlm.txt
Labels: CCB:Approved

#188 Fix #149, * might be referenced before assignment
  Subsystems/tlmGUI/GenericTelemetry.py
Labels: CCB:Ready, community

#192 cFS-GroundSystem Integration candidate: 2021-07-27
  README.md
  Subsystems/tlmGUI/GenericTelemetry.py
  Subsystems/tlmGUI/cfe-es-blockstats_1-tlm.txt
  Subsystems/tlmGUI/cfe-es-memstats-tlm.txt
  Subsystems/tlmGUI/cfe-tbl-hk-tlm.txt
  _version.py
Labels: community
