Repository nasa/cFS-GroundSystem, pull requests merged in 2021-02, with the labels that each got.

#152 Fix #151, Add static analysis and format check
  .github/workflows/format-check.yml
  .github/workflows/static-analysis.yml
  README.md
Labels: CCB:FastTrack, IC:2021-02-02, continuous-integration

#154 Fix #153, Add CodeQL analysis to workflow
  .github/workflows/codeql-build.yml
Labels: CCB:FastTrack, continuous-integration

#158 Fix #157, Apply formatting
  Subsystems/cmdUtil/SendUdp.c
  Subsystems/cmdUtil/cmdUtil.c
Labels: CCB:FastTrack

#156 Fix #155, Remove unnecessary type translations
  Subsystems/cmdGui/CHeaderParser.py
Labels: CCB:2021-02-17, IC:2021-02-23

#162 cFS-GroundSystem Integration candidate: 2021-02-23
  README.md
  Subsystems/cmdGui/CHeaderParser.py
  _version.py
Labels: IC:2021-02-23
